# Generated by Django 4.1.2 on 2022-10-06 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='contragents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('debit_credit', models.CharField(choices=[('debit', 'Приход'), ('credit', 'Расход')], max_length=20, verbose_name='тип операции')),
                ('amnt', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='сумма')),
                ('currency', models.CharField(max_length=255, verbose_name='валюта')),
                ('rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, verbose_name='Курс')),
                ('category', models.CharField(max_length=255, verbose_name='category')),
                ('tags', models.CharField(max_length=255, verbose_name='tags')),
                ('comments', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.accounts', verbose_name='Счет')),
                ('contragent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.contragents', verbose_name=' Контрагент')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.projects', verbose_name=' Контрагент')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.sources', verbose_name='Источник')),
            ],
        ),
    ]
