# Generated by Django 4.1.2 on 2022-10-06 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='contragents',
            options={'verbose_name': 'Контрагенты', 'verbose_name_plural': 'Контрагент'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='sources',
            options={'verbose_name': 'Загрузка', 'verbose_name_plural': 'Загрузки'},
        ),
        migrations.AddField(
            model_name='sources',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
