# Generated by Django 4.1.2 on 2022-10-06 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0002_alter_accounts_options_alter_contragents_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='checksum',
            field=models.CharField(default='', max_length=255, verbose_name='checksum'),
        ),
        migrations.AddField(
            model_name='sources',
            name='read_sheet',
            field=models.CharField(default=1, max_length=255, verbose_name='sheet'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='contragents',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='records',
            name='debit_credit',
            field=models.CharField(choices=[('debit', 'Приход'), ('credit', 'Расход'), ('transfer', 'Перевод')], max_length=20, verbose_name='тип операции'),
        ),
    ]
