# Generated by Django 4.1.2 on 2022-10-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_rename_checksum_records_chcksum_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='records',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='records',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='records',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tags'),
        ),
    ]
