# Generated by Django 4.1.2 on 2022-10-07 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0007_alter_records_category_alter_records_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='last_edit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_editor', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='records',
            name='debit_credit',
            field=models.CharField(choices=[('debit', 'Доход'), ('credit', 'Расход')], max_length=20, verbose_name='тип операции'),
        ),
    ]
