# Generated by Django 4.1.2 on 2022-10-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_records_last_edit_alter_records_debit_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='to_accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_accounts', to='first.accounts', verbose_name='На Счет'),
        ),
        migrations.AddField(
            model_name='records',
            name='to_contragent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_contragent', to='first.contragents', verbose_name='На Контрагент'),
        ),
    ]
