# Generated by Django 4.1.2 on 2022-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_alter_records_contragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='alt_interp',
            field=models.CharField(blank=True, choices=[('debit', 'Доход'), ('credit', 'Расход')], max_length=20, null=True, verbose_name='интерпретация операции'),
        ),
    ]
