# Generated by Django 4.1.2 on 2022-10-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_records_alt_interp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='alt_interp',
            new_name='debit_credit_alt',
        ),
    ]
