# Generated by Django 4.1.2 on 2022-10-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_rename_alt_interp_records_debit_credit_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_own',
            field=models.BooleanField(default=False, verbose_name='Наш?'),
        ),
        migrations.AddField(
            model_name='contragents',
            name='is_own',
            field=models.BooleanField(default=False, verbose_name='Наш?'),
        ),
    ]
