# Generated by Django 4.1.2 on 2022-10-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_accounts_is_own_contragents_is_own'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='accounts',
            new_name='account',
        ),
    ]
