# Generated by Django 4.1.2 on 2022-10-27 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0014_rename_accounts_records_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.accounts', verbose_name='cчет')),
                ('accounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ведущий счета')),
            ],
            options={
                'verbose_name': 'Право на счет',
                'verbose_name_plural': 'Права на счета',
            },
        ),
    ]
