# Generated by Django 4.1.2 on 2022-11-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_accounts_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=255, verbose_name='из валюта')),
                ('to_currency', models.CharField(max_length=255, verbose_name='в валюта')),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20, max_length=255, verbose_name='курс')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курс',
            },
        ),
        migrations.AlterField(
            model_name='records',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='records',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.projects', verbose_name='проект'),
        ),
    ]
