# Generated by Django 4.1.2 on 2022-11-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_rate_alter_records_category_alter_records_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rate',
            new_name='rates',
        ),
    ]
