# Generated by Django 4.1.2 on 2022-11-29 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_rename_rate_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='first.sources', verbose_name='Источник'),
        ),
    ]
