# Generated by Django 4.1.2 on 2022-11-30 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0019_accounts_permission_model_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts_permission',
            name='model_type',
        ),
        migrations.CreateModel(
            name='projects_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.projects', verbose_name='проект')),
                ('accounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ведущий проекта')),
            ],
            options={
                'verbose_name': 'Право на проект',
                'verbose_name_plural': 'Права на проекты',
            },
        ),
        migrations.CreateModel(
            name='contragents_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.contragents', verbose_name='контрагент')),
                ('accounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ведущий контрагент')),
            ],
            options={
                'verbose_name': 'Право на контрагент',
                'verbose_name_plural': 'Права на котрагент',
            },
        ),
    ]
